package shared

import (
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// userTmuxConfigSeed is the config Argus seeds once for the user (see
// SeedTmuxConfig) and then never overwrites. It carries no settings of its own:
// Argus's defaults live in the managed config, which sources this file after
// them, so an empty file here means "no overrides" rather than "no config".
const userTmuxConfigSeed = `# Your settings for Argus's dedicated tmux server. Argus writes this file once
# and never overwrites it, so anything you add survives upgrades.
#
# Argus's own defaults live in managed.conf beside this file. That one is
# regenerated on every start and sources this file *after* its defaults, so a
# setting here wins. The options it applies after the source-file line are ones
# the web UI is built on; those are re-applied last and cannot be overridden.
`

// managedTmuxConfig renders the config Argus owns for its dedicated tmux
// server: Argus's defaults, then the user's config, then the settings the web
// UI depends on. The order is the point — defaults first so the user's config
// can override them, the web UI's requirements last so it cannot.
//
// It is regenerated on every node start (see WriteManagedTmuxConfig), which is
// what lets a new default reach installs whose user config was seeded long ago.
// Nothing user-authored lives here, so overwriting loses nothing.
//
// history-limit is raised from tmux's default 2000 because that default bounds
// every look backwards: a wheel-scroll in the web terminal enters tmux
// copy-mode and reads this history, and `argus session peek --all` captures it.
// An agent's output blows past 2000 lines in minutes. 20000 sits under the web
// terminal's own 15000-line scrollback with room to spare, and history is
// allocated per pane as lines are produced, so idle sessions cost nothing.
//
// focus-events lets tmux forward focus in/out to the agent, which is what an
// agent running outside tmux would see from the terminal directly.
func managedTmuxConfig(userConfPath string) string {
	return `# Generated by Argus on every start — edits here are lost. Put your own
# settings in the config sourced below; Argus never overwrites that one.

# Defaults. The user config below is sourced after these, so it wins.
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"
set -g mouse on
set -g history-limit 20000
set -g focus-events on

source-file -q ` + quoteTmuxString(userConfPath) + `

# The web UI renders the session's identity in its own status bar, so tmux's
# would only repeat it at the cost of a row in every pane. Applied after the
# user config because the UI is built on its being off.
set -g status off
`
}

// quoteTmuxString renders s as a double-quoted tmux config string.
//
// tmux expands environment variables inside double quotes, so a path holding a
// literal $ has to be escaped along with the quote and escape characters
// themselves. Formats are not expanded — source-file only treats its argument
// as one under -F — so # and the rest pass through untouched.
func quoteTmuxString(s string) string {
	return `"` + strings.NewReplacer(`\`, `\\`, `"`, `\"`, `$`, `\$`).Replace(s) + `"`
}

// tmuxStateDir returns Argus's dedicated tmux directory: <StateDir>/tmux.
// Honors ARGUS_HOME so the dev stack is isolated.
func tmuxStateDir() (string, error) {
	dir, err := StateDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "tmux"), nil
}

// TmuxSocketPath returns the path to Argus's dedicated tmux server socket:
// <StateDir>/tmux/server.
//
// It rejects a path that cannot fit in sockaddr_un.sun_path (see
// maxTmuxSocketPath). tmux reports that case as "File name too long" against a
// path it only prints in passing, which reads as a missing-file problem rather
// than a length one; failing here instead names the limit at the single point
// every tmux caller goes through.
func TmuxSocketPath() (string, error) {
	dir, err := tmuxStateDir()
	if err != nil {
		return "", err
	}
	sock := filepath.Join(dir, "server")
	if len(sock) > maxTmuxSocketPath {
		return "", fmt.Errorf(
			"tmux socket path %q is %d bytes, over this platform's %d-byte unix socket limit; set ARGUS_HOME to a shorter path",
			sock, len(sock), maxTmuxSocketPath)
	}
	return sock, nil
}

// TmuxUserConfigPath returns the path to the user's tmux config:
// <StateDir>/tmux/tmux.conf. Argus seeds it once and never writes it again.
func TmuxUserConfigPath() (string, error) {
	dir, err := tmuxStateDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "tmux.conf"), nil
}

// TmuxManagedConfigPath returns the path to the config Argus owns:
// <StateDir>/tmux/managed.conf. This is the one the server is booted with; it
// sources the user's config in turn.
func TmuxManagedConfigPath() (string, error) {
	dir, err := tmuxStateDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "managed.conf"), nil
}

// EnsureTmuxStateDir creates Argus's dedicated tmux directory (<StateDir>/tmux)
// if missing and returns it. tmux places the dedicated server's socket here on
// first new-session, so this must succeed before any session can be created.
func EnsureTmuxStateDir() (string, error) {
	dir, err := tmuxStateDir()
	if err != nil {
		return "", err
	}
	if err := EnsureSecureDir(dir); err != nil {
		return "", fmt.Errorf("create tmux dir: %w", err)
	}
	return dir, nil
}

// TmuxCommand builds an *exec.Cmd that targets Argus's dedicated tmux server
// socket. It is the single place the -S flag is threaded; all callers (node
// and CLI) build their tmux commands through it.
func TmuxCommand(args ...string) (*exec.Cmd, error) {
	sock, err := TmuxSocketPath()
	if err != nil {
		return nil, err
	}
	full := append([]string{"-S", sock}, args...)
	return exec.Command("tmux", full...), nil
}

// TmuxCommandContext is TmuxCommand with a context for cancellation/timeout.
func TmuxCommandContext(ctx context.Context, args ...string) (*exec.Cmd, error) {
	sock, err := TmuxSocketPath()
	if err != nil {
		return nil, err
	}
	full := append([]string{"-S", sock}, args...)
	return exec.CommandContext(ctx, "tmux", full...), nil
}

// SeedTmuxConfig writes the user's tmux.conf into Argus's tmux directory only
// when it is missing, so a user-edited config is never overwritten. The
// directory must already exist (see EnsureTmuxStateDir). Returns the config path.
func SeedTmuxConfig() (string, error) {
	confPath, err := TmuxUserConfigPath()
	if err != nil {
		return "", err
	}

	tmp, err := writeTempTmuxConfig(confPath, userTmuxConfigSeed)
	if err != nil {
		return "", err
	}
	defer os.Remove(tmp)

	// Publish with a hard link. The link is atomic and fails with EEXIST when a
	// (possibly user-edited) config already exists, so we never overwrite it —
	// and a crash mid-write can only leave an orphan temp, never a truncated
	// tmux.conf that a later run would mistake for the user's own.
	if err := os.Link(tmp, confPath); err != nil {
		if errors.Is(err, os.ErrExist) {
			return confPath, nil
		}
		return "", fmt.Errorf("publish tmux config: %w", err)
	}
	return confPath, nil
}

// WriteManagedTmuxConfig regenerates the managed config, overwriting whatever
// is there. Unlike the user's config it holds nothing worth preserving, so it
// is rewritten on every node start — that is how a changed default reaches an
// install whose user config was seeded by an older version. The directory must
// already exist (see EnsureTmuxStateDir). Returns the config path.
func WriteManagedTmuxConfig() (string, error) {
	managedPath, err := TmuxManagedConfigPath()
	if err != nil {
		return "", err
	}
	userPath, err := TmuxUserConfigPath()
	if err != nil {
		return "", err
	}

	tmp, err := writeTempTmuxConfig(managedPath, managedTmuxConfig(userPath))
	if err != nil {
		return "", err
	}
	defer os.Remove(tmp)

	// Rename rather than link: overwriting is the point here, and rename is
	// atomic, so a server booting concurrently reads either the old config or
	// the new one, never a half-written file.
	if err := os.Rename(tmp, managedPath); err != nil {
		return "", fmt.Errorf("publish managed tmux config: %w", err)
	}
	return managedPath, nil
}

// writeTempTmuxConfig writes content to a durable temp file alongside dest and
// returns its path. The caller publishes it into place and removes the temp.
func writeTempTmuxConfig(dest, content string) (string, error) {
	tmp, err := os.CreateTemp(filepath.Dir(dest), "."+filepath.Base(dest)+"-*")
	if err != nil {
		return "", fmt.Errorf("create temp tmux config: %w", err)
	}
	if _, err := tmp.WriteString(content); err != nil {
		tmp.Close()
		os.Remove(tmp.Name())
		return "", fmt.Errorf("write tmux config: %w", err)
	}
	if err := tmp.Sync(); err != nil {
		tmp.Close()
		os.Remove(tmp.Name())
		return "", fmt.Errorf("sync tmux config: %w", err)
	}
	if err := tmp.Close(); err != nil {
		os.Remove(tmp.Name())
		return "", fmt.Errorf("close tmux config: %w", err)
	}
	return tmp.Name(), nil
}

// SourceManagedTmuxConfig loads the managed config into an already-running
// server. Booting with -f only applies the config to a server that is starting,
// so without this a changed default would wait for every session on the box to
// exit before it took effect. Options that panes read at creation time (notably
// history-limit) still only reach panes created after this call.
//
// A missing server is not an error: source-file does not start one, so on a
// fresh install this is a no-op and the -f at first new-session does the work.
func SourceManagedTmuxConfig() error {
	managedPath, err := TmuxManagedConfigPath()
	if err != nil {
		return err
	}
	cmd, err := TmuxCommand("source-file", managedPath)
	if err != nil {
		return err
	}
	out, err := cmd.CombinedOutput()
	if err == nil {
		return nil
	}
	if strings.Contains(string(out), "error connecting") {
		return nil
	}
	return fmt.Errorf("tmux source-file: %w: %s", err, strings.TrimSpace(string(out)))
}
